# Generated by Django 3.2 on 2022-05-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220515_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_handed',
        ),
    ]
